{% set version = "0.9.5" %}

package:
  name: cglm
  version: {{ version }}

source:
  url: https://github.com/recp/cglm/archive/v{{ version }}.tar.gz
  sha256: 1e40e87bc934ba8567ef84484d31d5d64ca084d3f0a7523ec67988bc94d76435
  patches:
    - windows_dll_name.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cglm', 'x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make    # [unix]
    - ninja   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libcglm${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\cglm.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\\lib\\cglm.lib exit 1    # [win]

about:
  home: https://github.com/recp/cglm
  summary: OpenGL Mathematics (glm) for C
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
