{% set version = "0.9.4" %}

package:
  name: cglm
  version: {{ version }}

source:
  url: https://github.com/recp/cglm/archive/v{{ version }}.tar.gz
  sha256: 101376d9f5db7139a54db35ccc439e40b679bc2efb756d3469d39ee38e69c41b
  patches:
    - windows_dll_name.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cglm', 'x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libcglm${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\cglm.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\\lib\\cglm.lib exit 1    # [win]

about:
  home: https://github.com/recp/cglm
  summary: OpenGL Mathematics (glm) for C
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
